name: Update Weekly Data

on:
  push:
    branches:
      - evidence  # Trigger on pushes to the 'evidence' branch
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install pandas requests duckdb numpy pyyaml markdown

      - name: Run Update Script
        run: python combined_download_script.py

      - name: Run Github stars script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python get_github_stars.py

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "dljtw98@gmail.com"
          git config --local user.name "Daniel ten Wolde"
          git add *
          git commit -m "Update daily download data"
          git push origin evidence